package animation

type AnimationState int

const (
	AnimationStateIdleRight = iota
	AnimationStateIdleDownRight
	AnimationStateIdleDown
	AnimationStateIdleDownLeft
	AnimationStateIdleLeft
	AnimationStateIdleUpLeft
	AnimationStateIdleUp
	AnimationStateIdleUpRight
	AnimationStateWalkRight
	AnimationStateWalkDownRight
	AnimationStateWalkDown
	AnimationStateWalkDownLeft
	AnimationStateWalkLeft
	AnimationStateWalkUpLeft
	AnimationStateWalkUp
	AnimationStateWalkUpRight
	AnimationStateRunRight
	AnimationStateRunDownRight
	AnimationStateRunDown
	AnimationStateRunDownLeft
	AnimationStateRunLeft
	AnimationStateRunUpLeft
	AnimationStateRunUp
	AnimationStateRunUpRight
)
