package animation

type AnimationState int

const (
	AnimationStateOffsetIdle = iota * 8
	AnimationStateOffsetWalk
	AnimationStateOffsetRun
	AnimationStateOffsetAim
	AnimationStateOffsetShoot
	AnimationStateOffsetHurt
)

const (
	AnimationStateIdleRight = iota
	AnimationStateIdleDownRight
	AnimationStateIdleDown
	AnimationStateIdleDownLeft
	AnimationStateIdleLeft
	AnimationStateIdleUpLeft
	AnimationStateIdleUp
	AnimationStateIdleUpRight
	AnimationStateWalkRight
	AnimationStateWalkDownRight
	AnimationStateWalkDown
	AnimationStateWalkDownLeft
	AnimationStateWalkLeft
	AnimationStateWalkUpLeft
	AnimationStateWalkUp
	AnimationStateWalkUpRight
	AnimationStateRunRight
	AnimationStateRunDownRight
	AnimationStateRunDown
	AnimationStateRunDownLeft
	AnimationStateRunLeft
	AnimationStateRunUpLeft
	AnimationStateRunUp
	AnimationStateRunUpRight
	AnimationStateAimRight
	AnimationStateAimDownRight
	AnimationStateAimDown
	AnimationStateAimDownLeft
	AnimationStateAimLeft
	AnimationStateAimUpLeft
	AnimationStateAimUp
	AnimationStateAimUpRight
	AnimationStateShootRight
	AnimationStateShootDownRight
	AnimationStateShootDown
	AnimationStateShootDownLeft
	AnimationStateShootLeft
	AnimationStateShootUpLeft
	AnimationStateShootUp
	AnimationStateShootUpRight
	AnimationStateHurtRight
	AnimationStateHurtDownRight
	AnimationStateHurtDown
	AnimationStateHurtDownLeft
	AnimationStateHurtLeft
	AnimationStateHurtUpLeft
	AnimationStateHurtUp
	AnimationStateHurtUpRight
)
